ALTER TABLE USER_PROGRAMS ADD NAME_SHORT VARCHAR(5) COLLATE UNICODE_CI_AI;
UPDATE RDB$FIELDS SET
RDB$FIELD_SUB_TYPE = 0
WHERE RDB$FIELD_NAME = (SELECT rf.RDB$FIELD_SOURCE
FROM RDB$RELATION_FIELDS rf
WHERE (rf.RDB$FIELD_NAME = 'ICON')
AND (rf.RDB$RELATION_NAME = 'USER_PROGRAMS'));
Commit;
ALTER TABLE USER_PROGRAMS ADD LOGIN_TYPE SMALLINT;
